langchain4j:
  open-ai:
    chat-model:
      api-key: ${API-KEY-ali}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${API-KEY-ali}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-flash
      log-requests: true
      log-responses: true
    embedding-model:
      api-key: ${API-KEY-ali}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v2
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10


logging:
  level:
    dev.langchain4j: DEBUG


spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动类
    url: jdbc:mysql://localhost:3307/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰-→下划线 命名映射

